import{useMemo,useState}from'react';import{analyzeReview,reviewExport,type Language,type Review}from'./domain/reviews';import AiMode from'./AiMode';import'./review-editor.css';
const reviews:Review[]=[{id:1,name:'Elena R.',rating:5,text:'Beautiful stay. The staff remembered our anniversary and breakfast was excellent.'},{id:2,name:'Jonas K.',rating:2,text:'The room was not clean when we arrived and we waited too long for help from the service team.'},{id:3,name:'Maha A.',rating:4,text:'الحجز كان سهلاً والفريق متعاون، لكن تسجيل الدخول استغرق وقتاً أطول من المتوقع.'}];
function App(){const[list,setList]=useState<Review[]>(reviews);const[active,setActive]=useState(2);const[language,setLanguage]=useState<Language>('English');const[approved,setApproved]=useState<number[]>([]);const[copied,setCopied]=useState(false);const review=list.find(x=>x.id===active)??list[0];const analysis=useMemo(()=>analyzeReview(review,language),[review,language]);const[custom,setCustom]=useState('');const response=custom||analysis.response;function select(id:number){setActive(id);setCustom('')}function editReview(key:keyof Review,value:string|number){setList(items=>items.map(item=>item.id===review.id?{...item,[key]:value}:item));setApproved(items=>items.filter(id=>id!==review.id));setCustom('')}async function copy(){await navigator.clipboard.writeText(response);setCopied(true);setTimeout(()=>setCopied(false),1700)}function add(){const id=Math.max(0,...list.map(x=>x.id))+1;setList(x=>[...x,{id,name:'New guest',rating:3,text:'Add the customer review here.'}]);select(id)}return <main>
<nav><a href="#top"><span>☺</span>KINDLY</a><p>Customer care studio / Lab 08</p><div><i/> Human approval required</div></nav>
<header id="top"><div><span>Listen carefully. Respond personally.</span><h1>Turn feedback into<br/><em>better relationships.</em></h1></div><aside><div><strong>{list.length}</strong><span>reviews in queue</span></div><div><strong>{list.filter(x=>x.rating<=2).length}</strong><span>need attention</span></div><div><strong>{approved.length}</strong><span>approved</span></div></aside></header>
<AiMode app="customer-review-assistant" payload={{review,language,localResult:analysis,editedResponse:response}} label="Draft response with AI"/>
<section className="desk"><aside className="inbox"><div className="inbox-head"><span>Review inbox</span><button onClick={add}>+ Add review</button></div>{list.map(r=>{const a=analyzeReview(r,'English');return <button className={`review-row ${active===r.id?'active':''}`} onClick={()=>select(r.id)} key={r.id}><div><b>{r.name}</b><span>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span></div><p>{r.text}</p><div><em>{a.category}</em><i className={a.sentiment.toLowerCase()}/><small>{approved.includes(r.id)?'Approved':a.priority}</small></div></button>})}</aside>
<div className="review-detail"><div className="detail-head"><label>Customer<input value={review.name} onChange={event=>editReview('name',event.target.value)} aria-label="Customer name"/></label><label>Rating<select value={review.rating} onChange={event=>editReview('rating',Number(event.target.value))} aria-label="Review rating"><option value="5">5.0</option><option value="4">4.0</option><option value="3">3.0</option><option value="2">2.0</option><option value="1">1.0</option></select></label></div><label className="review-copy">Original review<textarea className="review-text" value={review.text} onChange={event=>editReview('text',event.target.value)} aria-label="Review text"/></label><div className="signals"><div><span>Sentiment</span><b>{analysis.sentiment}</b></div><div><span>Topic</span><b>{analysis.category}</b></div><div><span>Priority</span><b>{analysis.priority}</b></div></div><div className="guidance"><span>Response guidance</span><ul><li>Acknowledge the specific experience</li><li>Avoid promises you cannot verify</li><li>Move personal follow-up to a private channel</li></ul></div></div>
<aside className="composer"><div className="composer-head"><span>Response draft</span><select value={language} onChange={e=>{setLanguage(e.target.value as Language);setCustom('')}}><option>English</option><option>German</option><option>Arabic</option></select></div><div className={`draft ${language==='Arabic'?'rtl':''}`}><span>Suggested reply / edit freely</span><textarea value={response} onChange={e=>setCustom(e.target.value)}/><small>{response.length} characters</small></div><div className="composer-actions"><button onClick={copy}>{copied?'Copied':'Copy response'}</button><button onClick={()=>setApproved(a=>a.includes(review.id)?a.filter(x=>x!==review.id):[...a,review.id])}>{approved.includes(review.id)?'Return to review':'Approve response'} ↗</button></div><button className="export" onClick={()=>navigator.clipboard.writeText(reviewExport(review,{...analysis,response}))}>Copy case note</button><p>No automatic publishing. Check names, facts, tone, and language before using any draft.</p></aside></section>
<footer><span>Designed & built by Jamil Darwish</span><span>Multilingual drafts · Human-owned response</span></footer></main>}
export default App;
